---
title: "ESS-DIVE Synoptic LE: Manual Redox - 2026 Submission Prep"
author: "Roberta Peixoto & Fausto Machado-Silva"
date: today
format:
  pdf:
    toc: true
    keep-tex: true
    output-dir: "LE-Synoptic-discrete-data/Manual_Redox_Probe_Data"

header-includes:
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(openxlsx)
library(knitr)
library(here)
```


## Pull in compiled data and export annual files
```{r Pull in compiled data files, message=FALSE, include=FALSE}

#write out a csv of all the data to the main folder: 
final_data <- read.csv("../COMPASS_SynopticLE_Redox_AllData.csv")

##Separate by year for ESS-DIVE 
final_data_2022 <- subset(final_data, Year == "2022")
final_data_2023 <- subset(final_data, Year == "2023")
final_data_2024 <- subset(final_data, Year == "2024")
final_data_2025 <- subset(final_data, Year == "2025")

##Write out annual data files
write.csv(final_data_2022, "Data package/COMPASS_SynopticLE_Manual Redox_2022.csv", row.names = FALSE)
write.csv(final_data_2023, "Data package/COMPASS_SynopticLE_Manual Redox_2023.csv", row.names = FALSE)
write.csv(final_data_2024, "Data package/COMPASS_SynopticLE_Manual Redox_2024.csv", row.names = FALSE)
write.csv(final_data_2025, "Data package/COMPASS_SynopticLE_Manual Redox_2025.csv", row.names = FALSE)

```


## Create dd file
```{r make metadata, include = FALSE}

#pull the column names from the all_dat1 dataframe and create a new dataframe with them
dd <- data.frame(Column_Names = colnames(final_data))
dd

dd$Unit <- ""
dd$Definition <- ""
dd$Column_Long_Name <- dd$Column_Names
dd$Data_Type <- ""
dd$Instrument_ifapplicable <- ""

#add information about each line:

dd$Definition <-  c("Project name",
                         "Region samples originated from: LE = Lake Erie",
                         "Year (YYYY) of sample collection",
                         "Month (MM) of sample collection",
                         "Day (DD) of sample collection",
                         "Time (HHMM) of sample collection",
                         "Time zone of sample collection",
                         "Site Code identifier for sampling transect location (CRC, OWC, PTR), see dataset locations for coordinates",
                         "Plot within space-for-time transect (UP=Upland, TR=Transition, WC=Wetland Center)",
                         "Plot topography particularities",
                         "Depth in centimeters below soil surface where measurement was taken",
                         "Average of field replicate measurements at the same depth (n=6) in millivolts", 
                         "Sample standard deviation calculated from field replicate measurements at the same depth (n=6) in millivolts.", 
                         "Sample standard error calculated from field replicate measurements at the same depth (n=6) in millivolts.", 
                         "Notes generated during field sample collection")

dd$Unit <-             c("NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "cm",
                         "mV",
                         "mV",
                         "mV",
                         "NA")

dd$Data_Type <-        c("text",
                         "text",
                         "numeric",
                         "text",
                         "numeric",
                         "numeric",
                         "text",
                         "text",
                         "text",
                         "text",
                         "numeric",
                         "numeric",
                         "numeric",
                         "numeric",
                         "text")

dd$Instrument_ifapplicable <-

                       c("NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "NA",
                         "Redox Probe: Paleo Terra Redox probe, Reference Probe: Ag/AgCl reference probe, Handheld Readout: Thermo Scientific Orion Star A221 pH Meter",
                         "NA",
                         "NA",
                         "NA")


#write out the data dictionary associated with the data:
write.csv(dd, "Data package/dd.csv", row.names = FALSE)

#write out data dictionary associated with the data to the main folder: 
write.csv(dd, here("Manual_Redox_Probe_Data/COMPASS_SynopticLE_Redox_Metadata.csv"), row.names = FALSE)

```


## Create flmd file
```{r create flmd}

files  = list.files("Data package")
files

files = c("COMPASS_SynopticLE_Manual Redox_2022.csv", "COMPASS_SynopticLE_Manual Redox_2023.csv", "COMPASS_SynopticLE_Manual Redox_2024.csv", "COMPASS_SynopticLE_Manual Redox_2025.csv", "dd.csv")

flmd <- data.frame(file_name = files)
flmd

flmd$file_description <- ""
flmd$standard <- ""
flmd$file_version <- ""
flmd$data_orientation <- ""
flmd$header_rows <- ""
flmd$column_or_row_name_position <- ""
flmd$notes <- ""

#add information about each line:

flmd$file_description <-  c("Manual redox data taken from COMPASS synoptic sites in 2022",
                            "Manual redox data taken from COMPASS synoptic sites in 2023",
                            "Manual redox data taken from COMPASS synoptic sites in 2024",
                            "Manual redox data taken from COMPASS synoptic sites in 2025",
                            "Data dictionary file for annual redox data files describing each column in the dataset")

flmd$data_orientation <-  c("horizontal",
                            "horizontal",
                            "horizontal",
                            "horizontal",
                            "horizontal")

flmd$header_rows <-   c("1",
                        "1",
                        "1",
                        "1",
                        "1")

flmd$column_or_row_name_position <- c("1",
                                      "1",
                                      "1",
                                      "1",
                                      "1")


#write out the flmd associated with the data:
write.csv(flmd, "Data package/flmd.csv", row.names = FALSE)

```


## Create site list
```{r create site list}

##Description, Latitude, Longitude

CRC <- data.frame(
  Description = "Crane Creek (CRC) one of the COMPASS_FME synoptic sites located in the Ottawa National Wildlife Refuge, approximately 2.9 miles west of the Ottawa National Wildlife Refuge Visitor Center, Ohio at the margin of the Crane Creek river. This synoptic site consists of three plots: upland ('UP'; located at 41.61524N, 83.22889W), transition ('TR'; 41.62192N, 83.23815W), and wetland ('WC'; 41.62185N, 83.2389W). The site was established in June 2022. ", 
  Latitude = "41.61524 degrees", 
  Longitude = "-83.22889 degrees")

OWC <- data.frame(
  Description = "Old Woman Creek (OWC) site is located at Old Woman Creek National Estuarine Research Reserve. This synoptic site consists of three plots: upland ('UP'; located at 41.37618N, 82.50685W), transition ('TR'; 41.376017N, 82.507507W), and wetland ('WC'; 41.376445N, 82.509024W). The site was established in June 2022.", 
  Latitude = "41.37618 degrees", 
  Longitude = "-82.50685 degrees")

PTR <- data.frame(
  Description = "Portage Rover (PTR), one of the COMPASS_FME synoptic sites located in the Ottawa National Wildlife Refuge’s Two Rivers unit, approximately 5.5 miles west of Port Clinton, Ohio at the confluence of the Portage and Little Portage rivers. This synoptic site consists of three plots: upland ('UP'; located at 41.50148N, 83.04611W), transition ('TR'; 41.502723N, 83.045662W), and wetland ('WC'; 41.50174N, 83.04372W). The site was established in June 2022.",
  Latitude = "41.50148 degrees", 
  Longitude = "-83.04611 degrees")

site_list = bind_rows(CRC, OWC, PTR)

#write out the site list associated with the data:
write.csv(site_list, "Data package/site_list.csv", row.names = FALSE)


```


## Data Description 
```{r data description}

#Create a text file that has the description of the data - This ideally should match the text that is in the data READ.ME 

datadescription <- "These data are measurements of soil reduction-oxidation potential (REDOX) profiles collected using REDOX probes at the COMPASS 'synoptic' sites in the Lake Erie region:  Crane Creek (CRC), Old Woman Creek (OWC), and Portage River (PTR). These sites have space for time transects spanning coastal upland forest (UP), coastal upland forest transitioning to wetland (TR), and wetland (WC) plots. Soil REDOX profiles were measured at 5, 10, and 20cm depths monthly from 2022-2024, then quarterly from 2024-2025 across the plots. To make measurements, one Ag/AgCl saturated KCl reference electrode was pushed into the soil a few centimeters and six replicate soil REDOX probes were pushed into the soil to the depth of measurement and allowed to equilibrate for five minutes before recording the probe reading with a Thermo Scientific Orion pH/ORP handheld meter. After the reading, probes were pushed to the next depth of interest. Raw measurements were recorded then adjusted to account for the Ag/AgCl saturated KCl reference electrode used."


#write to a text file 
writeLines(datadescription, "Data package/SynopticLE_Redox_ESSDIVE_DataDescription.txt")


```


## Create Author List 
```{r create author list}

#Pull in the common synoptic authors list: 
authors_common <- read.csv(here("Manual_Redox_Probe_Data/ESS-DIVE/COMPASS_SynopticLE_common_essdive_author_list.csv"))


#create a list of the last names you want to pull 
names_we_want <- c("Bittencourt Peixoto", "Machado-Silva", "Grammenidis","Bailey", "Weintraub")
order_of_authors <- c(1:length(names_we_want))

authors <- data.frame(
  order_of_authors = unlist(order_of_authors), 
  last_name = unlist(names_we_want)
)

#Subset the common list for the names that we want 
author_list <- authors %>% 
  left_join(authors_common, by = "last_name")

#if you need to add any other authors 
others <- data.frame(
  first_name = c("first_name1", "first_name2"), 
  last_name = c("last_name1", "last_name2"), 
  orcid = c("orcid_id1", "orcid_id2"), 
  affiliation = c("affiliation1", "affiliation2"), 
  email = c("email1", "email2"), 
  order_of_authors = c((length(names_we_want)+1):(length(names_we_want)+2))
)

#add in the other authors 
#author_list <- bind_rows(author_list, others)

#write out the author list associated with the data:
write.csv(author_list, "Data package/author_list.csv", row.names = FALSE)
```

